#pragma once
#include "../../common/service.h"

enum QID
{
	QID_PLAYER,
	QID_ITEM,
	QID_QUEST,
	QID_AFFECT,
	QID_LOGIN,
	QID_SAFEBOX_LOAD,
	QID_SAFEBOX_CHANGE_SIZE,
	QID_SAFEBOX_CHANGE_PASSWORD,
	QID_SAFEBOX_CHANGE_PASSWORD_SECOND,
	QID_PLAYER_DELETE,
	QID_LOGIN_BY_KEY,
	QID_PLAYER_INDEX_CREATE,
	QID_GUILD_RANKING,

#ifdef __OFFLINE_SHOP__
	QID_OFFLINESHOP_ADD_ITEM,

	QID_OFFLINESHOP_CREATE_SHOP,
	QID_OFFLINESHOP_CREATE_SHOP_ADD_ITEM,

	QID_OFFLINESHOP_SAFEBOX_ADD_ITEM,
#endif

#ifdef __SKILL_COLOR__
	QID_SKILL_COLOR,
#endif
#ifdef __BATTLE_PASS_SYSTEM__
	QID_BATTLE_PASS,
#endif
};