#ifndef __INC_PYTHON_uiscriptlib_MANAGER_H__
#define __INC_PYTHON_uiscriptlib_MANAGER_H__
#define inituiscriptlibManager inituiscriptlib
/* uiscriptlib module */
/* uiscriptlib.isExist */
/* uiscriptlib.moduleImport */
/* uiscriptlib.getList */
/* this lib includes modules under this lines.
	acceptguildwardialog
	acce_absorbwindow
	acce_combinewindow
	atlaswindow
	attachbonusdialog
	attachstonedialog
	autowindow
	banmanager
	battlepasswindow
	becerikitabi
	beltinventorywindow
	biologwindow
	cakrawindow
	calendarwindow
	changegradenamedialog
	changelookwindow
	changepassworddialog
	characterdetailswindow
	characterwindow
	chestdropwindow
	connectingdialog
	costumewindow
	createcharacterwindow
	cuberenewalwindow
	cuberesultwindow
	cubewindow
	declareguildwardialog
	deleteitem
	dragonsoulrefinewindow
	dragonsoulwindow
	dungeoninfowindow
	energybar
	eventinfodialog
	eventwindow
	exchangedialog
	expandedtaskbar
	gameoptiondialog
	gamewindow
	guildwindow
	guildwindow_boardpage
	guildwindow_gradepage
	guildwindow_guildinfopage_eu
	guildwindow_guildskillpage
	guildwindow_memberpage
	imekor
	inputdialog
	inputdialogwithdescription
	inputdialog_name
	inventorywindow
	inventorywindowex
	itemquestiondialog
	item_shop
	loadingwindow
	loadingwindowsub
	loginwindow
	mallwindow
	marklistwindow
	memleketwindow
	messengerwindow
	minimap
	moneyinputdialog
	moneyinputdialogwithcheque
	mountfeedwindow_n
	mounthatchingwindow_n
	mountinformationwindow_n
	mountminiinformationwindow_n
	mountnamechangewindow
	mousebuttonwindow
	movechanneldialog
	musiclistwindow
	offlineshopbuilder
	offlineshopeditwindow
	offlineshopsearchdialog
	offlineshopviewdialog
	OptionDlg
	partymemberinfoboard
	passworddialog
	petfeedwindow_n
	pethatchingwindow_n
	petinformationwindow_n
	petminiinformationwindow_n
	petnamechangewindow
	pickitemdialog
	pickmoneydialog
	pickmoneydialogwithcheque
	popupdialog
	popupdialog2
	popupdialogstream
	privateshopbuilder
	questdialog
	questiondialog
	questiondialog2
	questiondialog6
	questiondialog8
	questiondialogfastexit
	questiondialogmultiline
	questiondialogtimelimit
	questiondialogwithdescription
	rarity_refinedialog
	rebornwindow
	refinedialog
	remoteshopwindow
	restartdialog
	rightmousebuttonwindow
	ruhtasi
	rutbewindow
	safeboxwindow
	selectbonuslistwindow
	selectcharacterwindow
	selectempirewindow
	selectitemwindow
	shopdialog_ex
	skillchoosewindow
	skillcolorwindow
	skillpointresetdialog
	skillwindow
	specialstoragewindow
	systemdialog
	systemdialogex
	systemdialogex1024
	SystemExitDialog
	SystemExitDialog_1024
	systemoptiondialog
	systemswindow
	taskbar
	teleportwindow
	webwindow
	whisperdialog
	wiki
	wonexchangewindow
	_PrivateShopSearch
*/
void inituiscriptlibManager();
#endif
