#pragma once
class CAffect
{
public:
	DWORD	dwType;
	BYTE    bApplyOn;
	long    lApplyValue;
	DWORD   dwFlag;
	long	lDuration;
	long	lSPCost;

	static CAffect* Acquire();
	static void Release(CAffect* p);
};

enum EAffectTypes
{
	AFFECT_NONE,

	AFFECT_MOV_SPEED = 200,
	AFFECT_ATT_SPEED,		//201
	AFFECT_ATT_GRADE,		//202
	AFFECT_INVISIBILITY,	//203
	AFFECT_STR,				//204
	AFFECT_DEX,				//205
	AFFECT_CON,				//206
	AFFECT_INT,				//207
	AFFECT_FISH_MIND_PILL,	//208

	AFFECT_POISON,			//209
	AFFECT_STUN,			//210
	AFFECT_SLOW,			//211
	AFFECT_DUNGEON_READY,	//212
	AFFECT_DUNGEON_UNIQUE,	//213

	AFFECT_REVIVE_INVISIBLE,//214
	AFFECT_FIRE,			//215
	AFFECT_CAST_SPEED,		//216
	AFFECT_HP_RECOVER_CONTINUE,//217
	AFFECT_SP_RECOVER_CONTINUE,//218

	AFFECT_MOUNT,			//219

	AFFECT_WAR_FLAG,		//220

	AFFECT_BLOCK_CHAT,		//221
	AFFECT_CHINA_FIREWORK,	//222

	AFFECT_BOW_DISTANCE,	//223
	AFFECT_DEF_GRADE,		//224
#ifdef __WOLFMAN_CHARACTER__
	AFFECT_BLEEDING,		//225
#endif
	AFFECT_PREMIUM_START = 500,
	AFFECT_EXP_BONUS = 500,
	AFFECT_ITEM_BONUS = 501,
	AFFECT_SAFEBOX = 502,
	AFFECT_AUTOLOOT = 503,	// PREMIUM_AUTOLOOT,
	AFFECT_FISH_MIND = 504,	// PREMIUM_FISH_MIND,
	AFFECT_GOLD_BONUS = 506,
	AFFECT_PREMIUM_END = 509,

	AFFECT_MALL = 510,
	AFFECT_NO_DEATH_PENALTY = 511,
	AFFECT_SKILL_BOOK_BONUS = 512,
	AFFECT_SKILL_NO_BOOK_DELAY = 513,

	AFFECT_HAIR = 514,
	AFFECT_COLLECT = 515,
	AFFECT_EXP_BONUS_EURO_FREE = 516,
	AFFECT_EXP_BONUS_EURO_FREE_UNDER_15 = 517,
	AFFECT_UNIQUE_ABILITY = 518,

	AFFECT_BLEND = 531,

	AFFECT_HORSE_NAME,
	AFFECT_MOUNT_BONUS,

	AFFECT_AUTO_HP_RECOVERY = 534,
	AFFECT_AUTO_SP_RECOVERY = 535,

	AFFECT_DRAGON_SOUL_QUALIFIED = 540,
	AFFECT_DRAGON_SOUL_DECK_0 = 541,
	AFFECT_DRAGON_SOUL_DECK_1 = 542,
#ifdef __DS_SET_BONUS__
	NEW_AFFECT_DS_SET = 543,
#endif

#ifdef __GROWTH_PET_SYSTEM__
	AFFECT_NEW_PET = 559,
#endif

#ifdef __ICECREAM_ITEM__
	AFFECT_ICECREAM_ABILITY = 560,
#endif

#ifdef __GROWTH_MOUNT_SYSTEM__
	AFFECT_NEW_MOUNT = 561,
#endif

	AFFECT_RAMADAN_ABILITY = 600,
	AFFECT_RAMADAN_RING,//601

	AFFECT_NOG_ABILITY,//602
#ifdef __POTION_AS_REWORK__
	RED_BLEND_POTION,//603
	ORANGE_BLEND_POTION,//604
	YELLOW_BLEND_POTION,//605
	GREEN_BLEND_POTION,//606
	BLUE_BLEND_POTION,//607
	WHITE_BLEND_POTION,//608
	JADE_BLEND_POTION,//609
	DARK_BLEND_POTION,//610
	SAFE_BLEND_POTION,//611
	DEVIL_BLEND_POTION,//612
	HEAL_BLEND_POTION,//613
	NORMAL_HIT_BLEND_POTION,//614
	UNDEAD_BLEND_POTION,//615
	DEVIL_ATT_BLEND_POTION,//616
	ANIMAL_BLEND_POTION,//617
	MILGYO_BLEND_POTION,//618
#endif
#ifdef __DRAGON_BONE_EFFECT__
	AFFECT_DBONE_1,//619
	AFFECT_DBONE_2,//620
#endif
#ifdef __ALIGNMENT_REWORK__
	AFFECT_ALIGN_BONUS_TYPE_1,// 621
	AFFECT_ALIGN_BONUS_TYPE_2,// 622
	AFFECT_ALIGN_BONUS_TYPE_3,// 623
	AFFECT_ALIGN_BONUS_TYPE_4,// 624
	AFFECT_ALIGN_BONUS_TYPE_5,// 625
	AFFECT_ALIGN_BONUS_TYPE_6,// 626
	AFFECT_ALIGN_BONUS_TYPE_7,// 627
	AFFECT_ALIGN_BONUS_TYPE_8,// 628
#endif
#ifdef __BLEND_R_ITEMS__
	AFFECT_18385,//629
	AFFECT_18386,//630
	AFFECT_18387,//631
	AFFECT_18388,//632
	AFFECT_18389,//633
	AFFECT_18390,//634
#endif
#ifdef __RANK_SYSTEM__
	AFFECT_RANK_BONUS_TYPE_1,//636-1
	AFFECT_RANK_BONUS_TYPE_2,//637-1
	AFFECT_RANK_BONUS_TYPE_3,//638-1
	AFFECT_RANK_BONUS_TYPE_4,//639-1
	AFFECT_RANK_BONUS_TYPE_5,//640-1
	AFFECT_RANK_BONUS_TYPE_6,//641-1
	AFFECT_RANK_BONUS_TYPE_7,//642-1
	AFFECT_RANK_BONUS_TYPE_8,//643-1
	AFFECT_RANK_BONUS_TYPE_9,//644-1
	AFFECT_RANK_BONUS_TYPE_10,//645-1
	AFFECT_RANK_BONUS_TYPE_11,//646-1
	AFFECT_RANK_BONUS_TYPE_12,//647-1
	AFFECT_RANK_BONUS_TYPE_13,//648-1
	AFFECT_RANK_BONUS_TYPE_14,//649-1
	AFFECT_RANK_BONUS_TYPE_15,//650-1
	AFFECT_RANK_BONUS_TYPE_16,//651-1
	AFFECT_RANK_BONUS_TYPE_17,//652-1
#endif
#ifdef __LANDRANK_SYSTEM__
	AFFECT_LANDRANK_BONUS_TYPE_1,//653-1
	AFFECT_LANDRANK_BONUS_TYPE_2,//654-1
	AFFECT_LANDRANK_BONUS_TYPE_3,//655-1
	AFFECT_LANDRANK_BONUS_TYPE_4,//656-1
	AFFECT_LANDRANK_BONUS_TYPE_5,//657-1
	AFFECT_LANDRANK_BONUS_TYPE_6,//658-1
	AFFECT_LANDRANK_BONUS_TYPE_7,//659-1
	AFFECT_LANDRANK_BONUS_TYPE_8,//660-1
	AFFECT_LANDRANK_BONUS_TYPE_9,//661-1
	AFFECT_LANDRANK_BONUS_TYPE_10,//662-1
	AFFECT_LANDRANK_BONUS_TYPE_11,//663-1
	AFFECT_LANDRANK_BONUS_TYPE_12,//664-1
	AFFECT_LANDRANK_BONUS_TYPE_13,//665-1
	AFFECT_LANDRANK_BONUS_TYPE_14,//666-1
	AFFECT_LANDRANK_BONUS_TYPE_15,//667-1
	AFFECT_LANDRANK_BONUS_TYPE_16,//668-1
	AFFECT_LANDRANK_BONUS_TYPE_17,//669-1
	AFFECT_LANDRANK_BONUS_TYPE_18,//670-1
	AFFECT_LANDRANK_BONUS_TYPE_19,//671-1
	AFFECT_LANDRANK_BONUS_TYPE_20,//672-1
#endif
#ifdef __REBORN_SYSTEM__
	AFFECT_REBORN_BONUS_TYPE_1,//673-1
	AFFECT_REBORN_BONUS_TYPE_2,//674-1
	AFFECT_REBORN_BONUS_TYPE_3,//675-1
	AFFECT_REBORN_BONUS_TYPE_4,//676-1
	AFFECT_REBORN_BONUS_TYPE_5,//677-1
	AFFECT_REBORN_BONUS_TYPE_6,//678-1
	AFFECT_REBORN_BONUS_TYPE_7,//679-1
	AFFECT_REBORN_BONUS_TYPE_8,//680-1
	AFFECT_REBORN_BONUS_TYPE_9,//681-1
	AFFECT_REBORN_BONUS_TYPE_10,//682-1
#endif
#ifdef __SAGE_SKILL__
	AFFECT_SKILL_BOOK_BONUS2,
#endif
#ifdef __BIOLOG_SYSTEM__
	AFFECT_BIO_ITEM_DURATION,
	AFFECT_BIO_PACKET_DURATION,
	AFFECT_BIO_BONUS1,
	AFFECT_BIO_BONUS2,
	AFFECT_BIO_BONUS3,
	AFFECT_BIO_BONUS4,
	AFFECT_BIO_BONUS5,
	AFFECT_BIO_BONUS6,
	AFFECT_BIO_BONUS7,
	AFFECT_BIO_BONUS8,
#endif
#ifdef __FISH_BONUS_REWORK__
	AFFECT_FISH_EXP_BONUS,
	AFFECT_FISH_CAST_SPEED,
	AFFECT_FISH_MAX_HP,
	AFFECT_FISH_MAX_SP,
	AFFECT_FISH_ATTBONUS_UNDEAD,
	AFFECT_FISH_ATTBONUS_ANIMAL,
	AFFECT_FISH_ATTBONUS_MILGYO,
	AFFECT_FISH_ATTBONUS_ORC,
	AFFECT_FISH_ATTBONUS_DEVIL,
	AFFECT_FISH_ATTBONUS_INSECT,
	AFFECT_FISH_ATTBONUS_BOSS,
	AFFECT_FISH_ATTBONUS_MONSTER,
	AFFECT_FISH_ATTBONUS_HUMAN,
	AFFECT_FISH_ATTBONUS_STONE,
	AFFECT_FISH_NORMAL_HIT_BONUS,
	AFFECT_FISH_APPLY_STR,
	AFFECT_FISH_APPLY_DEX,
	AFFECT_FISH_APPLY_CON,
	AFFECT_FISH_APPLY_INT,
	AFFECT_FISH_APPLY_CAST_SPEED,
	AFFECT_FISH_APPLY_ATT_GRADE,
	AFFECT_FISH_APPLY_DEF_GRADE,
#endif
#ifdef __GROWTH_PET_SYSTEM__
	AFFECT_NEW_PET_DURATION,
#endif

#ifdef __CMD_EXTENSIONS__
	AFFECT_GM_BONUS_1,
	AFFECT_GM_BONUS_2,
	AFFECT_GM_BONUS_3,
	AFFECT_GM_BONUS_4,
	AFFECT_GM_BONUS_5,
	AFFECT_GM_BONUS_6,
	AFFECT_GM_BONUS_7,
	AFFECT_GM_BONUS_8,
	AFFECT_GM_BONUS_9,
	AFFECT_GM_BONUS_10,
#endif // __CMD_EXTENSIONS__
#ifdef __EXPERT_SKILL__
	AFFECT_SKILL_BOOK_BONUS_EXPERT,
#endif

	AFFECT_RAMADAN_NEW1,
	AFFECT_RAMADAN_NEW2,
	AFFECT_RAMADAN_NEW3,
	AFFECT_RAMADAN_NEW4,
	AFFECT_RAMADAN_NEW5,
	AFFECT_RAMADAN_NEW6,
	AFFECT_RAMADAN_NEW7,
	AFFECT_RAMADAN_NEW8,

#ifdef __SKILL_SET_BONUS__
	AFFECT_SEKILL_SET_BONUS_1,
	AFFECT_SEKILL_SET_BONUS_2,
	AFFECT_SEKILL_SET_BONUS_3,
	AFFECT_SEKILL_SET_BONUS_4,
	AFFECT_SEKILL_SET_BONUS_5,
	AFFECT_SEKILL_SET_BONUS_6,
#endif // __SKILL_SET_BONUS__

	AFFECT_ADAMSINIZ,
	AFFECT_KINDER,
	AFFECT_CIKOLATA,
	AFFECT_GUL,
	AFFECT_LOLIPOP,

#ifdef __EXPERT_SKILL__
	AFFECT_SKILL_BOOK_BONUS_DESTANSI,
	AFFECT_SKILL_BOOK_BONUS_TANRISAL,
#endif

#ifdef __LEVEL_SET_BONUS__
	AFFECT_LEVEL_SET_BONUS_1,
	AFFECT_LEVEL_SET_BONUS_2,
	AFFECT_LEVEL_SET_BONUS_3,
	AFFECT_LEVEL_SET_BONUS_4,
	AFFECT_LEVEL_SET_BONUS_5,
#endif // __LEVEL_SET_BONUS__

#ifdef __ITEM_SET_BONUS__
	AFFECT_ITEM_SET_BONUS_1,
	AFFECT_ITEM_SET_BONUS_2,
	AFFECT_ITEM_SET_BONUS_3,
	AFFECT_ITEM_SET_BONUS_4,
	AFFECT_ITEM_SET_BONUS_5,
#endif // __ITEM_SET_BONUS__

#ifdef __MONIKER_SYSTEM__
	AFFECT_MONIKER_BONUS_TYPE_1,
	AFFECT_MONIKER_BONUS_TYPE_2,
	AFFECT_MONIKER_BONUS_TYPE_3,
	AFFECT_MONIKER_BONUS_TYPE_4,
	AFFECT_MONIKER_BONUS_TYPE_5,
#endif // __MONIKER_SYSTEM__

#ifdef __TEAM_SYSTEM__
	AFFECT_TEAM_BONUS_TYPE_1,
	AFFECT_TEAM_BONUS_TYPE_2,
	AFFECT_TEAM_BONUS_TYPE_3,
	AFFECT_TEAM_BONUS_TYPE_4,
	AFFECT_TEAM_BONUS_TYPE_5,
#endif // __TEAM_SYSTEM__

#ifdef __POTION_AS_REWORK__
	AFFECT_NEW_SEBO_1,
	AFFECT_NEW_SEBO_2,
#endif // __POTION_AS_REWORK__

#ifdef __EXP_RING_ITEMS__
	AFFECT_NEW_EXP1,
	AFFECT_NEW_EXP2,
	AFFECT_NEW_EXP3,
	AFFECT_NEW_EXP4,
	AFFECT_NEW_EXP5,
	AFFECT_NEW_EXP6,
#endif

#ifdef __BATTLE_PASS_SYSTEM__
	AFFECT_BATTLE_PASS,
	AFFECT_BATTLE_PASS_PREMIUM,
#endif
#ifdef ENABLE_BATTLE_PASS_EX
	AFFECT_BATTLE_PASS_METIN,
	AFFECT_BATTLE_PASS_BOSS,
	AFFECT_BATTLE_PASS_MONSTER,
	AFFECT_BATTLE_PASS_BERSERKER,
	AFFECT_BATTLE_PASS_GUCLENDIRME,
	AFFECT_BATTLE_PASS_ORTALAMA,
#endif // ENABLE_BATTLE_PASS_EX

	AFFECT_OTOMATIKAV,

#ifdef ENABLE_PB2_PREMIUM_SYSTEM
	AFFECT_PB2_SKILL_COLOR,
	AFFECT_PB2_GLOBAL_CHAT,
#endif // ENABLE_PB2_PREMIUM_SYSTEM

#ifdef ENABLE_PB2_NEW_TAG_SYSTEM
	AFFECT_PB2_TAG_VIP,
	AFFECT_PB2_TAG_KING,
	AFFECT_PB2_TAG_QUEEN,
	AFFECT_PB2_TAG_MAFIA,
	AFFECT_PB2_TAG_BARON,
	AFFECT_PB2_TAG_STONE_KING,
	AFFECT_PB2_TAG_BOSS_KING,
	AFFECT_PB2_TAG_BARRIER,
#endif // ENABLE_PB2_NEW_TAG_SYSTEM

	AFFECT_BATTLE_PASS_BERSERKER_2,
	AFFECT_YILBASI,
	AFFECT_PB2_PET_NAME,
	AFFECT_PB2_MOUNT_NAME,
	AFFECT_PB2_CHAR_NAME,
	AFFECT_LOVE,
	AFFECT_WORD,
	AFFECT_BASLANGIC_ESYA,

	AFFECT_OTOAV_EFFECT,
#ifdef __GROWTH_MOUNT_SYSTEM__
	AFFECT_NEW_MOUNT_DURATION,
#endif

	AFFECT_KANAL_FIX,

#ifdef ENABLE_MULTI_FARM_BLOCK
	AFFECT_MULTI_FARM_PREMIUM,
#endif


	AFFECT_QUEST_START_IDX =	1000,
	AFFECT_QUEST_END_IDX =		100000
};

enum EAffectBits
{
	AFF_NONE,

	AFF_YMIR,
	AFF_INVISIBILITY,
	AFF_SPAWN,

	AFF_POISON,
	AFF_SLOW,
	AFF_STUN,

	AFF_DUNGEON_READY,
	AFF_DUNGEON_UNIQUE,

	AFF_MOV_SPEED_POTION,
	AFF_ATT_SPEED_POTION,

	AFF_FISH_MIND,

	AFF_JEONGWIHON,
	AFF_GEOMGYEONG,
	AFF_CHEONGEUN,
	AFF_GYEONGGONG,
	AFF_EUNHYUNG,
	AFF_GWIGUM,
	AFF_TERROR,
	AFF_JUMAGAP,
	AFF_HOSIN,
	AFF_BOHO,
	AFF_KWAESOK,
	AFF_MANASHIELD,
	AFF_MUYEONG,
	AFF_REVIVE_INVISIBLE,
	AFF_FIRE,
	AFF_GICHEON,
	AFF_JEUNGRYEOK,
	AFF_TANHWAN_DASH,
	AFF_PABEOP,
	AFF_CHEONGEUN_WITH_FALL,
	AFF_WAR_FLAG1,
	AFF_WAR_FLAG2,
	AFF_WAR_FLAG3,

	AFF_CHINA_FIREWORK,
	AFF_HAIR,
	AFF_GERMANY,
	AFF_RAMADAN_RING,

#ifdef __WOLFMAN_CHARACTER__
	AFF_BLEEDING,
	AFF_RED_POSSESSION,
	AFF_BLUE_POSSESSION,
#endif
#ifdef __DRAGON_BONE_EFFECT__
	AFF_DBONE1,
	AFF_DBONE2,
#endif
#ifdef __POTION_AS_REWORK__
	AFF_18385,
	AFF_18386,
	AFF_18387,
	AFF_18388,
	AFF_18389,
	AFF_18390,
#endif
#ifdef __DSS_ACTIVE_EFFECT__
	AFF_DRAGON_SOUL,
#endif
#ifdef ENABLE_PB2_NEW_TAG_SYSTEM
	AFF_PB2_TAG_VIP,
	AFF_PB2_TAG_KING,
	AFF_PB2_TAG_QUEEN,
	AFF_PB2_TAG_MAFIA,
	AFF_PB2_TAG_BARON,
	AFF_PB2_TAG_STONE_KING,
	AFF_PB2_TAG_BOSS_KING,
	AFF_PB2_TAG_BARRIER,
#endif
	AFF_OTOAV,
	AFF_BITS_MAX
};

extern void SendAffectAddPacket(LPDESC d, CAffect* pkAff, bool byLoad = false);

// AFFECT_DURATION_BUG_FIX
enum AffectVariable
{
	INFINITE_AFFECT_DURATION = 60 * 365 * 24 * 60 * 60
};
// END_AFFECT_DURATION_BUG_FIX