#ifndef __INC_PYTHON_rootlib_MANAGER_H__
#define __INC_PYTHON_rootlib_MANAGER_H__
#define initrootlibManager initrootlib
/* rootlib module */
/* rootlib.isExist */
/* rootlib.moduleImport */
/* rootlib.getList */
/* this lib includes modules under this lines.
	colorInfo
	constInfo
	emotion
	exception
	game
	game_settings
	grid
	interfaceModule
	introCreate
	introEmpire
	introLoading
	introLogin
	introSelect
	localeInfo
	m2_translate
	mouseModule
	musicInfo
	networkModule
	pb_ui
	playerSettingModule
	Prototype
	serverlogindata
	stringCommander
	system
	ui
	uiacce
	uiAffectShower
	uiattachbonus
	uiattachbonuslist
	uiAttachMetin
	uibanmanager
	uibecerikitabi
	uibiolog
	uiCandidate
	uichangelook
	uiCharacter
	uicharacterdetails
	uiChat
	uichestdrop
	uiCommon
	uiCube
	uicuberenewal
	uideleteitem
	uiDragonSoul
	uidungeoninfo
	uientitytracking
	uievent
	uieventcalendar
	uiEx
	uiExchange
	uiGameButton
	uigameoptionex
	uiGuild
	uiInventory
	uiitemshop
	uiMapNameShower
	uimemleket
	uiMessenger
	uiMiniMap
	uimountfeed
	uimountincubatrice
	uimountsystem
	uinewplayergauge
	uiofflineshopbuilder
	uiofflineshopedit
	uiofflineshopsearch
	uiofflineshopview
	uiParty
	uipetfeed
	uipetincubatrice
	uipetsystem
	uiPhaseCurtain
	uipickitem
	uiPickMoney
	uiPlayerGauge
	uiPointReset
	uiPrivateShopBuilder
	uiQuest
	uirarityrefine
	uireborn
	uiRefine
	uiRestart
	uiruhtasi
	uirutbe
	uiSafebox
	uiScriptLocale
	uiselectitem
	uiSelectMusic
	uiShop
	uiskill
	uiskillchoose
	uiskillcolor
	uispambot
	uispecialstorage
	uiswitchbot
	uiSystem
	uiTarget
	uiTaskBar
	uiteleport
	uiTip
	uiToolTip
	uiUploadMark
	uiWeb
	uiWhisper
	uiwhisperadmin
	uiwiki
	uiwiki_lbitem
	uiwiki_manager
	uiwonexchange
	ui_dropdown
	utils
	wrapper_class
*/
void initrootlibManager();
#endif
